name: Repository Maintenance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday
  workflow_dispatch:

jobs:
  format-r-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
          
      - name: Install R tools
        run: |
          install.packages(c('styler', 'formatR', 'knitr', 'rmarkdown'))
        shell: Rscript {0}
          
      - name: Check R formatting
        run: |
          library(styler)
          print("Files to be checked:")
          rfiles <- list.files(pattern = "\\.(R|Rmd)$", recursive = TRUE)
          print(rfiles)
          changes <- style_dir(".", dry = "on")
          print("Changes needed:")
          print(changes)
          if (length(changes) > 0) exit(1)
        shell: Rscript {0}

  create-format-pr:
    needs: format-r-code
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Create formatting branch
        run: |
          DATE=$(date +%Y%m%d_%H%M%S)
          echo "BRANCH_NAME=format-$DATE" >> $GITHUB_ENV
          git checkout -b format-$DATE
          
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install formatters
        run: |
          Rscript -e 'install.packages(c("styler", "formatR", "knitr", "rmarkdown"))'

      - name: Format code
        run: |
          Rscript -e 'styler::style_dir(".")'
          Rscript -e 'formatR::tidy_dir(".")'

      - name: Push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto format R code"
          git push origin format-$DATE

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'Auto: Format R code'
          body: 'Automated R code formatting changes'
          branch: ${{ env.BRANCH_NAME }}
          base: main

  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: 'This issue has been marked as stale due to 60 days of inactivity.'
          stale-pr-message: 'This PR has been marked as stale due to 60 days of inactivity.'
          days-before-stale: 60
          days-before-close: 7

  broken-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check broken links
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: "https://github.com/${{ github.repository }}"
          cmd_params: "--skip-tls-verification"

  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .

  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/dependency-review-action@v3

  size-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/xs'
          xs_max_size: '10'
          s_label: 'size/s'
          s_max_size: '100'
          m_label: 'size/m'
          m_max_size: '500'
          l_label: 'size/l'
          l_max_size: '1000'
          xl_label: 'size/xl'