name: Format Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
          
      - name: Install R tools
        run: |
          install.packages(c('styler', 'formatR', 'knitr', 'rmarkdown'))
        shell: Rscript {0}
          
      - name: Check R formatting
        run: |
          library(styler)
          print("Files to be checked:")
          rfiles <- list.files(pattern = "\\.(R|Rmd)$", recursive = TRUE)
          print(rfiles)
          changes <- style_dir(".", dry = "on")
          print("Changes needed:")
          print(changes)
          if (length(changes) > 0) exit(1)
        shell: Rscript {0}

  create-formatting-branch:
    needs: check-formatting
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Create formatting branch
        run: |
          DATE=$(date +%Y%m%d_%H%M%S)
          echo "BRANCH_NAME=format-$DATE" >> $GITHUB_ENV
          git checkout -b format-$DATE
          
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install formatters
        run: |
          Rscript -e 'install.packages(c("styler", "formatR", "knitr", "rmarkdown"))'

      - name: Format code
        run: |
          Rscript -e 'styler::style_dir(".")'
          Rscript -e 'formatR::tidy_dir(".")'

      - name: Push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto format R code"
          git push origin format-$DATE

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'Auto: Format R code'
          body: 'Automated R code formatting changes'
          branch: ${{ env.BRANCH_NAME }}
          base: main