name: Format Code

on:
  push:
    branches: [ main ]
    paths:
      - '**.R'
      - '**.Rmd'
  pull_request:
    branches: [ main ]
    paths:
      - '**.R'
      - '**.Rmd'
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::styler
            any::formatR
          
      - name: Format code
        run: |
          Rscript -e '
          library(styler)
          files <- list.files(pattern = "\\.(R|Rmd)$", recursive = TRUE)
          if (length(files) > 0) {
            style_dir(".")
          }'
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'style: format R code'
          title: 'style: format R code'
          body: |
            Automated R code formatting using styler package.
            
            - Formatted .R and .Rmd files
            - Applied tidyverse style guide
          branch: auto-format
          delete-branch: true
          labels: automated pr, formatting