on:
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Check out repo
        uses: actions/checkout@v3
      
      # 2. 安装并使用 Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      # 3. 执行 SonarCloud 扫描
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        env:
          # 确保在仓库 Settings → Secrets and variables → Actions 配置了 SONAR_TOKEN
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: |
            -Dsonar.projectKey=my-hse-mwi-project
            -Dsonar.organization=my-organization
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.exclusions=**/*.min.js,**/*.html,dist/**,build/**
