on:
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          args: |
            -Dsonar.projectKey=my-hse-mwi-project
            -Dsonar.organization=my-organization
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.exclusions=**/*.min.js, **/*.html, dist/**, build/**

