name: SonarCloud Scan

on:
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout
        uses: actions/checkout@v3

      # 2. 安装并使用 Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Install Required Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y which bash unzip wget
          
      # 3. 下载并解压 SonarScanner CLI
      - name: Install SonarScanner
        run: |
          wget -qO sonar-scanner.zip \
            https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip -q sonar-scanner.zip -d /tmp/sonar-scanner
          mv /tmp/sonar-scanner/sonar-scanner-4.8.0.2856-linux sonar-scanner
          echo "${{ github.workspace }}/sonar-scanner/bin" >> $GITHUB_ENV

      - name: Export Java Environment
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/temurin-17-jdk" >> $GITHUB_ENV
          echo "${{ github.workspace }}/sonar-scanner/bin:/usr/lib/jvm/temurin-17-jdk/bin:$PATH" >> $GITHUB_ENV

      # 4. 执行 SonarScanner
      - name: Run SonarScanner
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         JAVA_HOME: /usr/lib/jvm/temurin-17-jdk
         PATH: ${{ github.workspace }}/sonar-scanner/bin:/usr/lib/jvm/temurin-17-jdk/bin:$PATH
        run: |
          # 调试信息
          echo "JAVA_HOME=$JAVA_HOME"
          echo "PATH=$PATH"
          ls -l $JAVA_HOME/bin
          which java || true
          which sonar-scanner || true

          # 执行扫描
          sonar-scanner \
            -Dsonar.projectKey=my-hse-mwi-project \
            -Dsonar.organization=my-organization \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.exclusions="**/*.min.js,**/*.html,dist/**,build/**"
