name: SonarCloud

on:
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout
        uses: actions/checkout@v3

      # 2. 安装并使用 Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. 下载并解压 SonarScanner CLI
      - name: Install SonarScanner
        run: |
          wget -qO sonar-scanner.zip \
            https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner.zip
          mv sonar-scanner-4.8.0.2856-linux sonar-scanner
          # 也可以改为你需要的版本号
          # 将 sonar-scanner/bin 加入 PATH
          echo "${{ github.workspace }}/sonar-scanner/bin" >> $GITHUB_PATH

      # 4. 执行扫描
      - name: Run SonarScanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=my-hse-mwi-project \
            -Dsonar.organization=my-organization \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.exclusions="**/*.min.js,**/*.html,dist/**,build/**"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
