name: SonarCloud Scan

on:
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Check out repo
        uses: actions/checkout@v3

      # 2. 安装并使用 Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      # (可选) 查看当前 Java 版本，确认已切换成功
      - name: Check Java version
        run: java -version

      # 3. 下载并解压 SonarScanner CLI
      # （若你已经放在缓存或其他位置，可根据实际情况修改）
      - name: Install SonarScanner
        run: |
          wget -qO sonar-scanner.zip \
            https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner.zip
          mv sonar-scanner-4.8.0.2856-linux sonar-scanner
          # 将 sonar-scanner/bin 加入到 PATH，方便后续直接使用 'sonar-scanner' 命令
          echo "${{ github.workspace }}/sonar-scanner/bin" >> $GITHUB_PATH

      # 4. 执行 SonarScanner
      - name: Run SonarScanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=my-hse-mwi-project \
            -Dsonar.organization=my-organization \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.exclusions="**/*.min.js,**/*.html,dist/**,build/**"
        env:
          # 不要直接在脚本里写明文登录信息，而要通过 GitHub Secrets
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
