name: SonarCloud Scan

on:
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Uninstall existing Java and install OpenJDK 17
      - name: Set up JDK 17
        run: |
          sudo apt-get update
          sudo apt-get remove -y openjdk* || true
          sudo apt-get install -y openjdk-17-jdk
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          echo "export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> ~/.bashrc
          echo "export PATH=/usr/lib/jvm/java-17-openjdk-amd64/bin:$PATH" >> ~/.bashrc

      # 3. Install required tools
      - name: Install Required Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget

      # 4. Download and install SonarScanner
      - name: Install SonarScanner
        run: |
          wget -qO sonar-scanner.zip \
            https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip -q sonar-scanner.zip
          mv sonar-scanner-4.8.0.2856-linux sonar-scanner
          rm -rf sonar-scanner/jre
          export PATH=$PWD/sonar-scanner/bin:$PATH
          echo "export PATH=$PWD/sonar-scanner/bin:$PATH" >> ~/.bashrc

      # 5. Verify Java and SonarScanner installation
      - name: Verify Installation
        run: |
          cat ~/.bashrc
          pwd
          echo ">>> Checking Java and SonarScanner:"
          which java || true
          java -version || true
          which sonar-scanner || true
          sonar-scanner -v || true

      # 6. Run SonarScanner
      - name: Run SonarScanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          echo ">>> Running SonarScanner analysis..."
          sonar-scanner \
            -Dsonar.projectKey=my-hse-mwi-project \
            -Dsonar.organization=my-organization \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.exclusions="**/*.min.js,**/*.html,dist/**,build/**"
